name: never_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  dio: ^5.3.4
  pretty_dio_logger: ^1.4.0
  intl: ^0.19.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - .env